### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by ekkonap** [tudelft3d/cityjsonToRevit#1]
Hi, just here to follow up on the digigo accelleration meeting in Delft at 17/11. 
Loved your product! I have a few suggestions that might help you in future development. Just took a while to get around to finding your repository.

Use Air Photography as material texture
Use cityjson templates as Revit families (not for the rest, totally agree)
Material descriptions are available in the BGT dataset

Good luck!
Ekko Nap

**Comment by amiroo4** [comment]
Hi Ekko,

thanks for your comment and interest in the product.

I agree with you that cityjson templates can be best implemented through Revit families. Furthermore, the idea of using air photography as material textures is really fascinating. I would consider your suggestions for the future development.

Bests,
Amir Hakim
