### ISSUE TITLE
Revit Could not complete the external command

### ISSUE THREAD

**Issue by bjwprinsen** [tudelft3d/cityjsonToRevit#3]
Hi,
One of our users wants to work with the CityJSON plugin for Revit.
However, we cannot get the Plugin to work and every time we get the error message: "Revit could not complete the External command".
Can you help us with this?

Kind regards,

Berry Prinsen
BIM Application Manager | Van Wijnen Groep B.V.
![3Dgeoinfo](https://github.com/tudelft3d/cityjsonToRevit/assets/93973074/4d2da8f1-9ecb-417f-8d8e-80004f34c3e2)

**Comment by amiroo4** [comment]
Hi,
Thanks for your message. Can you check which Revit Version your user is using?
